on:
  push:
    branches: [develop, 'release/**']
    paths:
      - 'auth-service/**'
      - '.github/workflows/ci-auth-service.yml'

permissions:
  id-token: write
  contents: read
  security-events: write
  actions: read

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: auth-service
  GITOPS_REPO: ${{ vars.GITOPS_REPO }}

jobs:

  build:
    name: Build & Security Gates
    uses: ./.github/workflows/_java-build.yml
    with:
      service-name: auth-service
      service-dir: auth-service
      ecr-repository: auth-service
      aws-region: us-east-1
      needs-database: true
    secrets: inherit
